### ISSUE TITLE
How to use this lib...?

### ISSUE THREAD

**Issue by naeul-lee** [scholi/pyTOF#1]
I currently searching for the method of reading ION TOF raw data files, ITA, ITS, and ITM format.
However, I don't know how to use this modules..
I tried many times but I failed to use this successfully..

Please help me..!

**Comment by scholi** [comment]
Yes sorry, I'm developing several modules and the documentation is a bit delayed. I'll attached some examples / tutorial next week.

Regards

**Comment by scholi** [comment]
Here is a draft of the doc. It should be sufficient to start using the library:

https://github.com/scholi/pyTOF/blob/master/doc/pyTOF%20Documentation.ipynb

Kind regards

Olivier

**Comment by scholi** [comment]
Hey FAQ1,
Could you use the library? I have made several updates those last days. Now it should be much faster.
Tell me if you need more help.

Kind regards

Olivier
